//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adapter.TaifexGlobalPATS.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adapter.TaifexGlobalPATS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Contract Update 的當地語系化字串。
        /// </summary>
        internal static string Callbacks_ProcessContractUpdate_Contract_Update {
            get {
                return ResourceManager.GetString("Callbacks_ProcessContractUpdate_Contract_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}\{1}\{2} 的當地語系化字串。
        /// </summary>
        internal static string Callbacks_ProcessDOMUpdate__0___1___2_ {
            get {
                return ResourceManager.GetString("Callbacks_ProcessDOMUpdate__0___1___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ticker Price Exception Thrown {0}  的當地語系化字串。
        /// </summary>
        internal static string Callbacks_ProcessTickerPrice_Ticker_Price_Exception_Thrown__0__ {
            get {
                return ResourceManager.GetString("Callbacks_ProcessTickerPrice_Ticker_Price_Exception_Thrown__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error destroying clientAPI -  的當地語系化字串。
        /// </summary>
        internal static string ClientAPI_DestroyClientAPI_Error_destroying_clientAPI {
            get {
                return ResourceManager.GetString("ClientAPI_DestroyClientAPI_Error_destroying_clientAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Selector graphics loader failed 的當地語系化字串。
        /// </summary>
        internal static string ClientAPI_GetExChangeCount_Selector_graphics_loader_failed {
            get {
                return ResourceManager.GetString("ClientAPI_GetExChangeCount_Selector_graphics_loader_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Match found 的當地語系化字串。
        /// </summary>
        internal static string ClientAPI_GetOrderByID_match_found {
            get {
                return ResourceManager.GetString("ClientAPI_GetOrderByID_match_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Depth Market Callback issued 的當地語系化字串。
        /// </summary>
        internal static string ClientAPI_PutDomUpdate_Depth_Market_Callback_issued {
            get {
                return ResourceManager.GetString("ClientAPI_PutDomUpdate_Depth_Market_Callback_issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Null reference incountered in PutDomUpdate 的當地語系化字串。
        /// </summary>
        internal static string ClientAPI_PutDomUpdate_Null_reference_incountered_in_PutDomUpdate {
            get {
                return ResourceManager.GetString("ClientAPI_PutDomUpdate_Null_reference_incountered_in_PutDomUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exception In Ticker Price UpDate {0} 的當地語系化字串。
        /// </summary>
        internal static string ClientAPI_putTickerObject_Exception_In_Ticker_Price_UpDate__0_ {
            get {
                return ResourceManager.GetString("ClientAPI_putTickerObject_Exception_In_Ticker_Price_UpDate__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Null reference incountered in PutTraderPriceUpdateObject 的當地語系化字串。
        /// </summary>
        internal static string ClientAPI_PutTraderPriceUpdateObject_Null_reference_incountered_in_PutTraderPriceUpdateObject {
            get {
                return ResourceManager.GetString("ClientAPI_PutTraderPriceUpdateObject_Null_reference_incountered_in_PutTraderPrice" +
                        "UpdateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exception when adding orders :  的當地語系化字串。
        /// </summary>
        internal static string ClientAPI_stubBuildObjects_Exception_when_adding_orders {
            get {
                return ResourceManager.GetString("ClientAPI_stubBuildObjects_Exception_when_adding_orders", resourceCulture);
            }
        }
    }
}
